carrot 80
chicken breast 170
cucumber 300
egg 55
garlic 4
garlic clove 4
green bell pepper 180
green pepper 180
lemon wedges 120
lime wedge 50
onion 180
red bell pepper 180
red chilli 12
red pepper 180
spring onion 15
tomato 120
tofu 300
bean sprout 30
