bean sprout 30
bird's eye chilli 5
brown onion 180
canned tuna in olive oil 185
carrot 80
cheese 20
chicken breast 170
choy sum 80
cooked rice 200
cooked white rice 200
cucumber 300
egg 55
flat-leaf parsley 10
fresh red chilli 12
frozen dumpling 25
garlic 4
garlic clove 4
green bell pepper 180
green pepper 180
instant ramen 85
lemon wedges 120
lime 60
lime wedge 50
onion 180
red bell pepper 180
red chili 12
red chilli 12
red onion 150
red pepper 180
shallot 30
spring onion 15 x8
tofu 300
tomato 120
white bread 35
lemon 120
chicken thigh 150
corn cob 160
mango 200
chilli 10
pork sausage 60
sweet potato 300
dry red chilli 1
smoked bacon rasher 25
bay leaf 0.2
celery stick 40 x5
kale 200
coriander 30
parsley 30
